param(
    [string]$OutputFile = "LINT_CHECKLIST.md"
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path $MyInvocation.MyCommand.Path -Parent
$projectDir = Split-Path $scriptDir -Parent
$outputPath = Join-Path $projectDir $OutputFile

Write-Host "Running eslint with JSON output..." -ForegroundColor Cyan

# Use cmd /c to properly separate stdout from stderr
$jsonString = cmd /c "npx eslint src/**/*.{ts,tsx,js} --format json 2>nul" 2> $null

$results = $jsonString | ConvertFrom-Json

$totalErrors = 0
$totalWarnings = 0
foreach ($file in $results) {
    $totalErrors += $file.errorCount
    $totalWarnings += $file.warningCount
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Lint Error Checklist")
$lines.Add("")
$lines.Add("Всего: **$($totalErrors + $totalWarnings)** проблем ($totalErrors ошибок, $totalWarnings предупреждений)")
$lines.Add("")
$lines.Add("## Ошибки по файлам")
$lines.Add("")

$hasProblems = $false

foreach ($file in $results | Sort-Object filePath) {
    if ($file.messages.Count -eq 0) { continue }
    $hasProblems = $true

    $relativePath = $file.filePath -replace [regex]::Escape($projectDir + "\"), ""
    $lines.Add("### $relativePath")
    $lines.Add("")

    foreach ($msg in $file.messages) {
        $ruleId = if ($msg.ruleId) { "**" + $msg.ruleId + "**" } else { "**unknown**" }
        $severity = if ($msg.severity -eq 2) { "error" } else { "warning" }
        $cleanMessage = $msg.message -replace "`r`n", " " -replace "`n", " "
        $line = "- [ ] [$severity] " + $ruleId + ": " + $cleanMessage + " (строка " + $msg.line + ")"
        $lines.Add($line)
    }

    $lines.Add("")
}

if (-not $hasProblems) {
    $lines.Add("No errors found!")
    $lines.Add("")
}

$lines.Add("---")
$lines.Add("")
$lines.Add("_Generated by scripts/lint-to-checklist.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')_")

$lines -join "`r`n" | Out-File -FilePath $outputPath -Encoding utf8

Write-Host "Checklist saved to $outputPath" -ForegroundColor Green
Write-Host "Problems: $totalErrors errors, $totalWarnings warnings" -ForegroundColor Yellow
